# Generated by Django 4.2.5 on 2023-12-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_customer_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='username',
        ),
    ]
