# Generated by Django 4.2.5 on 2023-12-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.district'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='materials_provide',
        ),
        migrations.AddField(
            model_name='customer',
            name='materials_provide',
            field=models.ManyToManyField(blank=True, to='bankapp.material'),
        ),
    ]
