# Generated by Django 4.2.5 on 2023-12-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_alter_customer_branch_alter_customer_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(default='default-slug', editable=False, unique=True),
        ),
    ]
