# Generated by Django 4.2.5 on 2023-12-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_alter_district_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
